### ISSUE TITLE
staticpublishqueue breaks on SSL sites

### ISSUE THREAD

**Issue by Rexeh** [silverstripe-labs/silverstripe-staticpublishqueue#20]
Due to the way paths are referenced, utilising site-wide SSL causes complete site failure due to previously relative paths being referenced as absolutes with static publish.

For example /themes/ becoming http://domain.com/themes/theme/* causing load failures from a different domain.

Would be nice to introduce better handling of this...

**Comment by lingo** [comment]
I tried specifying `static_base_url` in config, but found this didn't work when the cache was build via sake.
I found it worked only when I set the following in my config files.

    Director:
        alternate_protocol: 'https'
