### ISSUE TITLE
Module doesn't work with default SS functionality

### ISSUE THREAD

**Issue by Rexeh** [silverstripe-labs/silverstripe-staticpublishqueue#29]
When using page level access rules (Show only to "These people" in groups etc) and utilising the "Show in menus" element - The caching prevent access to the restricted page.

Being a module from SS, would expect it to work as standard with default SS3 functionality?

**Comment by Rexeh** [comment]
Any update on this?

**Comment by dhensby** [comment]
Full page caching is an aggressive caching approach. Known limitations of this kind of caching will be that it doesn't vary from user to user; you'll always serve the same page to every used.

The best you'll get is probably going to be modifying the module to skip the static cache for logged in users.

I'm going to close this as a "known limitation"
